### ISSUE TITLE
Strange results from shd file

### ISSUE THREAD

**Issue by bbbrandyn** [A-New-BellHope/bellhopcuda#22]
After replacing the original bellhop.exe with bellhopcxx2d.exe renamed to bellhop.exe, any .env I run produces this striped output. Tried v1.4 and v1.31. The example shows plotshd of the 'DickinsB.env' test found in the Acoustics Toolbox.

![bellhopcxx_](https://github.com/A-New-BellHope/bellhopcuda/assets/136633941/d7838aed-6b75-45f6-98d2-1acfa97a6b75)
[DickinsBenv.txt](https://github.com/A-New-BellHope/bellhopcuda/files/11971755/DickinsBenv.txt)

**Comment by oldstylejoe** [comment]
Thanks for feedback! Could you please check which version of the Matlab plotting routines you're using? In the 2023 version of the Acoustics toolbox, the binary .shd file format changed from single to double precision. bellhopcxx/cuda is based on the 2022 version. DickinsB should work with the plotting routines from at_2022_4_20.

**Comment by bbbrandyn** [comment]
Thank you for the fast reply! Ah, I am using the 2023 version so that must be the problem. Do you know where the 2022 version is available? On the other hand, if one were to use bellhopcxx as the library version, how could one plot the transmission loss in a similar fashion to the matlab plotting routines?

**Comment by oldstylejoe** [comment]
The 2020 Acoustic Toolbox on the [oalib site](http://oalib.hlsresearch.com/AcousticsToolbox/) also supports single precision .shd.
Plotting from the library would take a little more work and depend on how you run the library. The pressure data are available as a raw array of complex numbers, and [examples/defaults.cpp](https://github.com/A-New-BellHope/bellhopcuda/blob/main/examples/defaults.cpp) shows how you can output the pressure from C++.

**Comment by bbbrandyn** [comment]
I plotted the results using the 2020 acoustic toolbox and I got the expected results. I wouldn't be too sure how to plot the complex numbers so I'll stick to the matlab plotting routines for now. Thank you for your help!
