### ISSUE TITLE
How to read the generated file

### ISSUE THREAD

**Issue by wang-yuhao123** [A-New-BellHope/bellhopcuda#34]
I used cmd to navigate to the root directory and ran 'bellhop.exe --2D' on a '.env' file in text format. It generated a '.shd' file without any errors. How should I use this file, or what changes should I make to my running method? This is my first time debugging the project and there are many things I don't understand. Thank you for your guidance.

**Comment by oldstylejoe** [comment]
Thanks for using bellhopcuda. As a standalone program, bellhop is a drop-in replacement for the Fortran version that has its own history and user guide. You can find some examples here - http://oalib.hlsresearch.com/AcousticsToolbox/at_2022_4_20.zip

If there's something specific you'd like help with, please let me know.

**Comment by wang-yuhao123** [comment]
How to see if bellhop is accelerated by cuda?

**Comment by wang-yuhao123** [comment]
I don't know how to open the generated .shd and .prt files. Regular 3D software shows that they cannot be opened. Is it because the way I generate the files using the command line is incorrect, or is there another way to generate them? (My method is to place bellhopcxx.exe in the root directory, then put the .env file I want to generate there as well, and then enter bellhopcxx.exe --2D along with the desired output file in the command line.)
