### ISSUE TITLE
Bellhopcuda/Bellhopcxx occur incorrect result( *.arr ).

### ISSUE THREAD

**Issue by JAY-JIWON** [A-New-BellHope/bellhopcuda#41]
Greetings,

I'd like to use Bellhopcuda/Bellhopcxx(c++) instead of Bellhop(fortran) on ideal under-water environment.
But the result of arrival( *.arr ) contatins incorrent information, at Bellhopcuda/Bellhopcxx.
I did not build the source code, just use pre-compiled binaries ( [bellhopcxx / bellhopcuda v1.41](https://github.com/A-New-BellHope/bellhopcuda/releases/tag/1.41) )
Please check this issue.

![IncorrectResult](https://github.com/user-attachments/assets/75e62883-1083-4880-b261-7f9101055fec)

**[ Test Environment ]** : [analysis.env.txt](https://github.com/user-attachments/files/18033054/analysis.env.txt), [analysis.bty.txt](https://github.com/user-attachments/files/18033062/analysis.bty.txt)

- Frequency : 4 kHz
- SSP : 1500 m/s ( Isovelocity )
- BTY : 1000 m ( flat )
- Sender / Receiver depth : 100 m
- Range : 1.5 km
  
**[ Bellhopcuda/Bellhopcxx Result ]** : [analysis.arr.txt](https://github.com/user-attachments/files/18033090/analysis.arr.txt)
```
'2D'
   4000.0000000000000     
           1   100.000000    
           1   100.000000    
           1   1500.00000    
           3
           3
   1.20919292E-04   180.000000      0.995726526       0.00000000      -7.73999977       7.73999977               1           0
   5.33582934E-04   180.000000       1.00938392       0.00000000      -7.55999994       7.55999994               1           0
  NAN               0.00000000      -NAN(IND)        -NAN(IND)        -1.66533454E-15   0.00000000               0           0
```

**[ Bellhop(fortran) Result ]** : [analysis_base.arr.txt](https://github.com/user-attachments/files/18033183/analysis_base.arr.txt)
```
 '2D'
   4000.0000000000000     
           1   100.000000    
           1   100.000000    
           1   1500.00000    
           3
           3
   1.27160572E-04   180.000000       1.00884652       0.00000000      -7.73999977       7.73999977               1           0
   5.33656916E-04   180.000000       1.00884950       0.00000000      -7.55999994       7.55999994               1           0
   6.66666660E-04   0.00000000       1.00000000       0.00000000       0.00000000       0.00000000               0           0
```

**Comment by oldstylejoe** [comment]
Thanks for sending this, and after some investigation, I'm pretty sure it's from my previous bad fix for the arrival time, combined with the ray happening to exactly contact a receiver. It should be fixed [here](https://github.com/A-New-BellHope/bellhopcuda/pull/42). Can you please take a look and check if that resolves your issue? I'm happy to send/link an executable if you'd rather (just let me know your system).
We're still working to resolve the arrival bug fully, but this at least will agree with the FORTRAN version.

**Comment by JAY-JIWON** [comment]
Thx for check this issue rapidly :)
For check this issue, I build the latest source code by using cmake file, and use the new executable file.
But, the result of arrival is same with before ( it contains incorrent information ).
Could you plz double check this?

![IncorrectResult_2](https://github.com/user-attachments/assets/6198cb1c-0ab3-42ae-a36b-45286c59d93f)

**Comment by oldstylejoe** [comment]
Thanks for trying and I'm glad cmake worked ok. Sorry for the unclear instructions. The changes are on a branch that hasn't been pulled into main yet. Can you please try the [RevertNormFix1](https://github.com/A-New-BellHope/bellhopcuda/tree/RevertNormFix1) branch? It looks like you downloaded a zip file, and the corresponding zip file is [here](https://github.com/A-New-BellHope/bellhopcuda/archive/refs/heads/RevertNormFix1.zip).

**Comment by JAY-JIWON** [comment]
Ah, thanks for your kindness.
Using the branch source code, the result contains correct result :)

![Result](https://github.com/user-attachments/assets/09c728d6-ae2c-42f9-941c-543fc736cac5)

**Comment by oldstylejoe** [comment]
Great! I'll merge it into main and upload binaries. This should close this issue.
